mutation CreateCategory($name: String!, $status: String!) @auth(level: PUBLIC) {
  category_insert(data: { name: $name, status: $status })
}

mutation CreateUnit($name: String!, $status: String!) @auth(level: PUBLIC) {
  unit_insert(data: { name: $name, status: $status })
}

mutation CreateSize($name: String!, $status: String!) @auth(level: PUBLIC) {
  size_insert(data: { name: $name, status: $status })
}

mutation CreateProduct(
  $name: String!
  $hsn: String
  $code: String
  $categoryId: String
  $unitId: String
  $sizeId: String
  $gst: Float!
  $rate: Float!
  $stock: Int!
  $description: String
  $status: String!
) @auth(level: PUBLIC) {
  product_insert(data: {
    name: $name
    hsn: $hsn
    code: $code
    categoryId: $categoryId
    unitId: $unitId
    sizeId: $sizeId
    gst: $gst
    rate: $rate
    stock: $stock
    description: $description
    status: $status
  })
}

mutation CreateCustomer(
  $name: String!
  $gstin: String
  $mobile: String!
  $mobile2: String
  $email: String
  $address: String!
  $stateId: String
  $districtId: String
  $talukId: String
  $pincode: String
  $status: String!
) @auth(level: PUBLIC) {
  customer_insert(data: {
    name: $name
    gstin: $gstin
    mobile: $mobile
    mobile2: $mobile2
    email: $email
    address: $address
    stateId: $stateId
    districtId: $districtId
    talukId: $talukId
    pincode: $pincode
    status: $status
  })
}

mutation CreateSupplier(
  $name: String!
  $contactPerson: String
  $gstin: String
  $mobile: String!
  $mobile2: String
  $email: String
  $address: String!
  $stateId: String
  $districtId: String
  $talukId: String
  $pincode: String
  $status: String!
) @auth(level: PUBLIC) {
  supplier_insert(data: {
    name: $name
    contactPerson: $contactPerson
    gstin: $gstin
    mobile: $mobile
    mobile2: $mobile2
    email: $email
    address: $address
    stateId: $stateId
    districtId: $districtId
    talukId: $talukId
    pincode: $pincode
    status: $status
  })
}

mutation CreateState($name: String!, $status: String!) @auth(level: PUBLIC) {
  state_insert(data: { name: $name, status: $status })
}

mutation CreateDistrict($name: String!, $stateId: String!, $status: String!) @auth(level: PUBLIC) {
  district_insert(data: { name: $name, stateId: $stateId, status: $status })
}

mutation CreateTaluk($name: String!, $districtId: String!, $status: String!) @auth(level: PUBLIC) {
  taluk_insert(data: { name: $name, districtId: $districtId, status: $status })
}

mutation UpdateCustomer(
  $id: String!
  $name: String!
  $gstin: String
  $mobile: String!
  $mobile2: String
  $email: String
  $address: String!
  $stateId: String
  $districtId: String
  $talukId: String
  $pincode: String
  $status: String!
) @auth(level: PUBLIC) {
  customer_update(id: $id, data: {
    name: $name
    gstin: $gstin
    mobile: $mobile
    mobile2: $mobile2
    email: $email
    address: $address
    stateId: $stateId
    districtId: $districtId
    talukId: $talukId
    pincode: $pincode
    status: $status
  })
}

mutation DeleteCustomer($id: String!) @auth(level: PUBLIC) {
  customer_delete(id: $id)
}

mutation UpdateSupplier(
  $id: String!
  $name: String!
  $contactPerson: String
  $gstin: String
  $mobile: String!
  $mobile2: String
  $email: String
  $address: String!
  $stateId: String
  $districtId: String
  $talukId: String
  $pincode: String
  $status: String!
) @auth(level: PUBLIC) {
  supplier_update(id: $id, data: {
    name: $name
    contactPerson: $contactPerson
    gstin: $gstin
    mobile: $mobile
    mobile2: $mobile2
    email: $email
    address: $address
    stateId: $stateId
    districtId: $districtId
    talukId: $talukId
    pincode: $pincode
    status: $status
  })
}

mutation DeleteSupplier($id: String!) @auth(level: PUBLIC) {
  supplier_delete(id: $id)
}
